### ISSUE TITLE
Problem after update 1.1.0

### ISSUE THREAD

**Issue by Dotmatrix812** [Sickboy78/MMM-Homematic#10]
I have a problem after update of MMM-Homematic

I don't know why, the log says:

`0|MagicMirror  | [18.01.2022 20:45.03.491] [ERROR] 
0|MagicMirror  | App threw an error during load
0|MagicMirror  | [18.01.2022 20:45.03.497] [ERROR] 
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-Homematic/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | - 
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
0|MagicMirror  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:94:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Homematic/node_helper.js:3:17)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|MagicMirror  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
0|MagicMirror  | [18.01.2022 20:45.03.501] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [18.01.2022 20:45.03.526] [ERROR] 
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-Homematic/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | - 
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
0|MagicMirror  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:94:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Homematic/node_helper.js:3:17)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|MagicMirror  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10) {
0|MagicMirror  |   code: 'MODULE_NOT_FOUND',
0|MagicMirror  |   requireStack: [
0|MagicMirror  |     '/home/pi/MagicMirror/modules/MMM-Homematic/node_helper.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/app.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMirror  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMirror  |     undefined
0|MagicMirror  |   ]
0|MagicMirror  | }
0|MagicMirror  | [18.01.2022 20:45.03.529] [ERROR] 
`

**Comment by Sickboy78** [comment]
Hi @Dotmatrix812 ,

I forgot to add the dependency to the request module, my bad.
Please update again and then run 'npm install' in the MMM-Homematic folder to install all required dependencies.

Regards

**Comment by Dotmatrix812** [comment]
Hi @Sickboy78,

wow, it works. Thanks for the fast help.

Regards
