### ISSUE TITLE
Installation experience and XML-API

### ISSUE THREAD

**Issue by Lateadapter** [Sickboy78/MMM-Homematic#11]
@Sickboy78 and @spitzlbergerj 

Hi both,
first I want to thank you for providing such nice module. I have tried in recent weeks several capabilities to show on MM data from my "smart home zoo", e.g. MMM-MQTT, MMM-ioBroker and now also MMM-Homematic. I'm not at all a programmer. So far I faced many challenges in introducing customizations. In the end I was able to achieve the best results with your module. I particularly like the ability to use custom local icons.
I'm running the MM in server mode as docker container on Synology NAS. Homematic is runnig as Raspberrymatic on Pi 3.
The physical mirror itself is disconnected from integration and just using fullpageos on Raspi.

Following few issues, I faced:

1. After installation the module was shown on MM only with headline and permanent "loading ..." message. It took me days to find out that the cause of the problem was a security setup in the Homematic-GUI. The option "Redirect to https" under "System control/ Security..." need to be unchecked! Otherwise there won't be any connection to the XML-API. It doesn't matter, if in the MMM the configuration option "ccuProtocol" will be choosen "http://" or "https://" - the only working combination was "http:" in the module and the unchecked box in CCU.
![CCU_security](https://user-images.githubusercontent.com/122560017/212556710-20f1fb9e-3b5e-428b-9a06-58d9a11243fd.png)

2. Looking for the route cause of the issue above I found some important information about running refactoring activities of XML-API https://homematic-forum.de/forum/viewtopic.php?f=41&t=77234
It would be very pitty, if after introduction of announced XML-API update the MMM-Homematic Module won't work anymore. Hopefully you are trying to cover the compatibility in future as well. 

3. Special types , like ä, ü, ö (Umlaute) or the degrees sign (°) were not shown correctly in the data point section independent from definition for "locale". I did solve that "quick and dirty" by choosing special characters according https://toolstud.io/web/charmap.php?filter=*

4. I would have one wish to consider for future development: Beside the styles "lines" and "tables" it would be nice to have the possibility to write few data points one after each other in one line. It would better use the entire space of an mirror region. The sample below I did generate with the MMM-ioBroker
![sample_ioBroker](https://user-images.githubusercontent.com/122560017/212559735-353f6f64-ee22-4ced-ab3a-338da76a2192.png)

Again many thanks for your work and best regards from Thuringia,
Steffen

**Comment by Sickboy78** [comment]
Hi Steffen,

thx for the detailed description and analysis, which really makes it easier for me to understand and reproduce the issues.
Also thx for the notice of the upcoming change in XML-API.
As for the issues:

1. I disabled the SSL certificate check in version 1.1.1 that now allows self signed certifcates which I guess is the issue here. At least I could reproduce it and fix it for me this way. Feedback is welcome, whether it works for you too.
2. I added a warning to the readme, that you have to stay on XML-API 1.x for now. When I have more time, I will try to implement the authentication for version 2.x.
3. I can't reproduce this issue. Umlaute are wörking for me.
![grafik](https://user-images.githubusercontent.com/8673383/213938502-fac2e3f7-5a42-4202-8f52-7b549c07098b.png)
My guess would be a wrong encoding of the config.js. Make sure it is UTF-8-BOM. You can check and change the encoding for example with notepad++.
4. I'll put it on my todo list.

Best Regards

PS.: Grüße von Bayern nach Thüringen ;)

**Comment by Lateadapter** [comment]
Hi Sebastian,

many thanks for the fast response.
Regarding the issues...
1. Now it's working, very good.
   However, currently I have to leave the mentioned checkbox unchecked, because some other usecase is generating similar issues. Actual it's the nonworking connection from HomeAssistant to Homematic. But finally I'm sure the issue will disappear, because all related SW-packages (Raspberrymatic, XML-API and HASS-Integration) are managed by same developer.
2. Sounds good!!
3. You are absolutely right. Many thanks for that useful hint :) . First time I heard about. My MM is running on Synology under Docker and I did all the customization using the existing Text-Editor. Just now I realized, that even that editor has the option for different codings. And btw few other modules were affected ... few not.
4. Very much appreciated - thx!

Viele Grüße !
Steffen

![image](https://user-images.githubusercontent.com/122560017/214081543-608a22f1-e525-4322-b14c-da4ae7ae50b8.png)

**Comment by Sickboy78** [comment]
Hi Steffen,

have a look at the new style single_line in latest version 1.1.3.
Hope that's what you need for point 4.

Regards

**Comment by Lateadapter** [comment]
Hallo Sebastian,

it works very well as expected. Many thanks for your effort!

Regards,
Steffen

**Comment by Lateadapter** [comment]
Hi Sebastian,

I just want to give a hint that actual there is an update for refactored XML-API, which very probably wont work together with the MMM-Homematic module: [https://github.com/homematic-community/XML-API](url)
Hopefully you will find some time in future for diving in...

Best regards, Steffen

**Comment by Sickboy78** [comment]
Hi Steffen,

I implemented the authentication for XML-API 2.x in the new version 1.2.0.
Just create a token for the XML-API and add it as _ccuXmlApiTokenId_ in your module config and you should be fine.
Tested it with XML-API 2.1.

Best Regards

**Comment by Lateadapter** [comment]
Hi Sebastian,
tested with XML-API 2.2. - works perfect. Many thanks!

Steffen
