### ISSUE TITLE
"sysvar_number_warn_high" and "precision (of datapoint) =2" not working

### ISSUE THREAD

**Issue by Lateadapter** [Sickboy78/MMM-Homematic#12]
Hi Sebastian,

recently I found some issue with "sysvar_number_warn_high" and "precision (of datapoint)".  If I use precision = "0" than everything works fine. But if I change to precision= "2" than "threshold (of datapoint)" will not work anymore (no icon color change).
However same datapoint using type "other_warn_high" works fine (but generates as expected not required message).
There seems to be a slightly different implementation of both data point types.

A sample usecase is an amount of money in format "x.xx".

Regards, Steffen

**Comment by Sickboy78** [comment]
Hi Steffen,

thx for submitting this bug.
Should be fixed in the latest version 1.1.2.

Regards

**Comment by Lateadapter** [comment]
It works... many thanks for the fast fix!
Steffen
