### ISSUE TITLE
short text title - how does this work now?

### ISSUE THREAD

**Issue by spitzlbergerj** [Sickboy78/MMM-Homematic#8]
Hi,
in my pull request there were two fields `name `and `nameShort`. The latter was used in the tables.
How does this work now if `useShortText `was set? In which field must the short text be placed?

Thanks

**Comment by spitzlbergerj** [comment]
And in the table view the titles were above the icons. Is that still possible now?

**Comment by Sickboy78** [comment]
Hi Josef!
I removed the nameShort because I think it's redundant. If you want short text, just put it in the name. useShortText just uses the short output of the state/value and the short translations. But you can convince me otherwise, see my comments at the merge request.

**Comment by Sickboy78** [comment]
As for the icons, you can use iconPositon to set the icon position to top, center or bottom row.

**Comment by spitzlbergerj** [comment]
Thanks for the notes in the pull request comments. So I could restore "my" old layout. Thanks
