### ISSUE TITLE
Error after update to 2.18.0

### ISSUE THREAD

**Issue by carstendirks** [Sickboy78/MMM-Homematic#9]
After updating MagicMirror to 2.18.0 I am getting errors running MMM-Homematic:

`Access to XMLHttpRequest at 'http://192.168.178.xx/addons/xmlapi/state.cgi?datapoint_id=1824' from origin 'http://0.0.0.0:8080' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.`

Because of this there is no data retrieved from the XML API anymore.

Do you have any suggestions how to solve this?

(There is also a similar discussion: https://forum.magicmirror.builders/topic/16131/mmm-hue-cors-policy-issue?page=1)

**Comment by Sickboy78** [comment]
Hi,
I just updated to MM 2.18.0 and I can't reproduce it. For me everythings working fine, so I can't give you any suggestions right now. I have to dive deeper into it.

Can you give me some more information?
Where does this error show up, in the MM logs or in the browser console?
Which version of the XML Api are you using? (/addons/xmlapi/version.cgi)
What http headers are returned on the above request? (especially the CORS related ones like Access-Control-Allow-Origin)

Regards

**Comment by carstendirks** [comment]
Thanks for the support!

I found the errors in the browser console. You also have to make an NPM install which installs a new node version - I guess only updating to 2.18.0 will not make a difference.

XML API version is 1.21

Where can I find the http header information? Is this in the logs?

**Comment by Sickboy78** [comment]
Ok, I'll try to update NPM as well. But I'm busy right now, could take some days ...

You can find the http headers in the network tab of the browser developer tools when selecting the request under answerheaders.

![grafik](https://user-images.githubusercontent.com/8673383/148692949-e7694842-f0cc-4696-8db5-f16456bb646b.png)

**Comment by carstendirks** [comment]
`Request URL: http://192.168.178.45/addons/xmlapi/state.cgi?datapoint_id=1824
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.178.45:80
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, must-revalidate, no-transform, max-age=0
Content-Length: 95
Content-Type: text/xml
Date: Sun, 09 Jan 2022 17:27:16 GMT
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Host: 192.168.178.45
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.98 Safari/537.36

**Comment by Sickboy78** [comment]
Quick workaround until I have time to fix, if you only access the magicmirror on locahost:
Change address in config.js from "0.0.0.0" to something else, e.g "" or "127.0.0.1".

**Comment by carstendirks** [comment]
Yes - that works. Thanks a lot. (Should have known this myself...)

**Comment by Sickboy78** [comment]
Hi @carstendirks ,

I did a refactoring of the module and moved the xml api requests to the backend (node_helper.js), so they are no longer done with jquery. This should fix the issue and allow the use of adress: "0.0.0.0" in the config again.

Best Regards

**Comment by carstendirks** [comment]
Works perfect, thank you again!
